In [ ]:
from google.colab import drive
drive.mount('/content/drive')


%cd /content/drive/MyDrive/ML_DATASET/papaya/Fresh Papaya Leaf/clahe

import numpy as np                       
import tensorflow as tf
import matplotlib.pyplot as plt
from numpy import linalg as LA

from sklearn.preprocessing import StandardScaler



from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_curve, auc

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/ML_DATASET/papaya/Fresh Papaya Leaf/clahe

In [ ]:
import glob
import cv2 as cv
import pandas as pd
import numpy as np
images4=[cv.imread(file,cv.IMREAD_UNCHANGED) for file in sorted(glob.glob(r"/content/drive/MyDrive/ML_DATASET/papaya/Fresh Papaya Leaf/clahe/*.png"))]

In [ ]:
! pip install -q tensorflow-model-optimization
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
import tensorflow_model_optimization as tfmot
li=[]

for i,img in enumerate(images4):
    model = Sequential()
    model.add(Dense(1024, activation='relu', kernel_initializer='he_normal', input_shape=(65536,)))
    
    model.add(Dense(512, activation='relu', kernel_initializer='he_normal'))
    model1 =tfmot.sparsity.keras.prune_low_magnitude(model)
    # compile the model
    model1.compile()
    # fit the model
    img=img.reshape(1,256*256)
    img=img.astype('float64')

  
    from tensorflow.keras import backend as K
    layerIndex = 1
    func = K.function([model1.get_layer(index=0).input], model1.get_layer(index=layerIndex).output)
    layerOutput = func([img])  # input_data is a numpy array
    
    li.append(layerOutput[0])

/usr/local/lib/python3.7/dist-packages/tensorflow_model_optimization/python/core/sparsity/keras/pruning_wrapper.py:218: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use `layer.add_weight` method instead.
  aggregation=tf.VariableAggregation.MEAN)
/usr/local/lib/python3.7/dist-packages/tensorflow_model_optimization/python/core/sparsity/keras/pruning_wrapper.py:225: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use `layer.add_weight` method instead.
  aggregation=tf.VariableAggregation.MEAN)
/usr/local/lib/python3.7/dist-packages/tensorflow_model_optimization/python/core/sparsity/keras/pruning_wrapper.py:238: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use `layer.add_weight` method instead.
  trainable=False)

In [ ]:
df=pd.DataFrame(li)

In [ ]:
col=df.columns
cnt =0
for i in col:
  if(df[i]==0):
    cnt=cnt+1

print(cnt)

ValueError: ignored

In [ ]:
df1=pd.read_csv(r"/content/drive/MyDrive/ML_DATASET/papaya/Fresh-Papaya-Leaf.csv")

In [ ]:
df1.drop(df1.tail(3).index,inplace=True)

In [ ]:
df_concat = pd.concat([df1, df], axis=1)

In [ ]:
df_concat.columns

Index(['Unnamed: 0',          '0',          '1',          '2',          '3',
                '4',          '5',          '6',          '7',          '8',
       ...
                502,          503,          504,          505,          506,
                507,          508,          509,          510,          511],
      dtype='object', length=530)

In [ ]:
df_concat.drop('Unnamed: 0',axis=1,inplace=True)

In [ ]:
df_concat

,0,1,2,3,4,5,6,7,8,9,...,502,503,504,505,506,507,508,509,510,511
0,0.234528,0.417839,0.305576,0.445275,0.968219,0.959598,0.961888,0.954640,0.751434,0.747761,...,25.698883,0.000000,0.000000,0.000000,217.094894,0.000000,281.432770,0.000000,0.000000,185.663071
1,0.277849,0.410427,0.256893,0.448812,0.964054,0.955821,0.959657,0.951342,0.730503,0.726977,...,0.000000,78.406670,0.000000,234.769577,0.000000,340.814606,29.342045,0.000000,181.091888,0.000000
2,0.226624,0.351465,0.211213,0.332026,0.960360,0.950425,0.957193,0.948394,0.774682,0.771835,...,207.715302,154.031418,93.057938,33.673843,0.000000,223.312408,302.712250,45.031982,76.809860,174.344559
3,0.287255,0.560692,0.392448,0.527782,0.958271,0.945471,0.950368,0.945401,0.693165,0.687682,...,0.000000,32.908482,53.706852,405.201691,0.000000,88.231964,0.000000,0.000000,0.000000,192.363922
4,0.296477,0.546974,0.398545,0.584760,0.964779,0.956820,0.958611,0.953378,0.551095,0.546756,...,0.000000,0.000000,0.000000,0.000000,0.000000,244.804108,0.000000,0.000000,478.437714,0.000000
5,0.313863,0.674648,0.494853,0.673187,0.961918,0.949672,0.953838,0.947866,0.592264,0.586600,...,363.205719,0.000000,0.000000,0.000000,98.769524,157.115189,4.650434,268.753540,510.732910,134.320801
6,0.315962,0.452288,0.267693,0.447090,0.949730,0.942511,0.947723,0.941044,0.573783,0.569599,...,98.950012,0.000000,0.000000,0.000000,258.504761,66.943542,0.000000,0.000000,332.728516,0.000000
7,0.293964,0.437709,0.289185,0.480492,0.957318,0.948205,0.951780,0.941322,0.706066,0.702219,...,0.000000,272.668335,14.036561,0.000000,248.286316,250.501144,0.000000,0.000000,0.000000,328.442963
8,0.278355,0.557017,0.432475,0.644014,0.971356,0.963326,0.965049,0.960898,0.562262,0.556121,...,0.000000,0.000000,338.843750,0.000000,0.000000,0.000000,0.000000,148.798904,0.000000,27.549940
9,0.291176,0.593695,0.440196,0.596048,0.961203,0.948609,0.952724,0.946211,0.529638,0.522211,...,294.374817,0.000000,0.000000,477.171295,0.000000,201.843979,267.151184,63.106960,0.000000,0.000000
10,0.603462,1.664867,1.410937,1.771872,0.942138,0.913238,0.916917,0.912515,0.765450,0.758976,...,0.000000,379.240021,0.000000,191.878342,0.000000,0.000000,0.000000,64.910667,161.448517,145.162811
11,0.603431,1.664898,1.410846,1.771872,0.942135,0.913223,0.916927,0.912515,0.765450,0.758976,...,37.546730,46.836941,0.000000,0.000000,181.209656,0.000000,0.000000,0.000000,0.000000,0.000000
12,0.295665,0.536209,0.393336,0.574271,0.970326,0.963042,0.964706,0.961191,0.593848,0.588435,...,285.836884,0.000000,0.000000,245.856628,0.000000,0.000000,0.000000,0.000000,198.197495,127.535423
13,0.292218,0.505267,0.330928,0.491688,0.955536,0.945543,0.950179,0.944854,0.505779,0.498770,...,0.000000,0.000000,288.567810,297.161743,328.454468,0.000000,24.305511,160.660187,0.000000,253.476059
14,0.746906,2.269589,1.928707,2.235879,0.926319,0.887647,0.889450,0.883584,0.733236,0.724783,...,0.000000,0.000000,0.000000,9.442993,0.000000,26.646133,0.000000,0.000000,430.904114,0.000000
15,0.667310,1.556878,1.260815,1.680892,0.940709,0.916556,0.918481,0.911144,0.738487,0.732810,...,202.597290,0.000000,305.165009,541.437683,120.607445,91.128906,0.000000,0.000000,60.625404,335.271240
16,0.667310,1.556878,1.260815,1.680892,0.940709,0.916556,0.918481,0.911144,0.738487,0.732810,...,0.000000,0.000000,0.000000,150.379410,114.188538,170.084167,0.000000,0.000000,0.000000,326.793457
17,0.755208,2.191280,1.775398,2.161138,0.947110,0.916051,0.920963,0.915153,0.776461,0.768422,...,167.031799,20.330404,0.000000,0.000000,324.966156,0.000000,0.723878,0.000000,100.273430,153.308655
18,0.751654,2.175409,1.766023,2.156309,0.947473,0.916497,0.921221,0.915266,0.776443,0.768405,...,111.314789,195.034729,244.825546,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,41.776962
19,0.359206,0.656963,0.479182,0.718155,0.960047,0.953311,0.954999,0.948475,0.599950,0.596771,...,164.053650,0.000000,0.000000,58.328636,0.000000,0.000000,0.000000,186.623901,95.169426,297.729340
20,0.282276,0.509527,0.314323,0.457286,0.973510,0.966743,0.969948,0.966944,0.629044,0.625032,...,347.102936,0.000000,0.000000,0.000000,362.041107,643.791077,0.000000,0.000000,198.114990,0.000000

In [ ]:
#df_concat.to_csv("/content/drive/MyDrive/ML_DATASET/papaya/fresh_hand_deep.csv")