In [ ]:

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn import metrics,preprocessing
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import roc_curve, roc_auc_score
from sklearn.model_selection import GridSearchCV
from sklearn import svm
from sklearn.naive_bayes import GaussianNB
from imblearn.over_sampling import SMOTE
from sklearn import preprocessing

In [ ]:


df=pd.read_csv(r"/content/drive/MyDrive/ML_DATASET/papaya/black_spot_hand_deep.csv")
df1=pd.read_csv(r"/content/drive/MyDrive/ML_DATASET/papaya/curl_hand_deep.csv")
df2=pd.read_csv(r"/content/drive/MyDrive/ML_DATASET/papaya/fresh_hand_deep.csv")
df3=pd.read_csv(r"/content/drive/MyDrive/ML_DATASET/papaya/powder_hand_deep.csv")
df4=pd.read_csv(r"/content/drive/MyDrive/ML_DATASET/papaya/ring_spot_hand_deep.csv")

In [ ]:
df_combined=pd.concat([df,df1,df2,df3,df4])

In [ ]:
df_combined

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,502,503,504,505,506,507,508,509,510,511
0,0,1.544899,2.757586,2.114691,2.947605,0.758675,0.691885,0.726238,0.681630,0.355424,...,0.000000,0.000000,0.000000,0.000000,0.000000,120.588394,161.390350,251.83319,0.000000,4.827495
1,1,1.292540,2.024498,1.226394,2.233110,0.871023,0.812662,0.863136,0.808404,0.460534,...,0.000000,22.223488,133.775620,0.000000,0.000000,0.985636,0.000000,140.70679,0.000000,0.000000
2,2,1.806939,2.824175,1.457353,2.787605,0.804783,0.727017,0.812520,0.729335,0.420484,...,401.947100,0.000000,0.000000,0.000000,98.988050,0.000000,254.501450,0.00000,0.000000,0.000000
3,3,1.201517,1.970211,1.940610,2.218239,0.698044,0.704844,0.635543,0.686536,0.318765,...,0.000000,207.658050,281.388520,81.959460,111.806710,74.203140,213.555970,379.69147,0.000000,67.750110
4,4,0.552819,0.872664,0.618459,0.975548,0.909786,0.885553,0.898913,0.881536,0.585466,...,73.526920,0.000000,0.000000,0.000000,286.341670,0.000000,440.736760,74.89989,58.192330,54.025833
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,66,3.169072,3.498624,1.728493,4.318431,0.619404,0.605221,0.703047,0.575884,0.218107,...,0.000000,0.000000,103.233734,15.188221,35.710697,275.709800,0.000000,0.00000,71.536674,259.301600
67,67,1.238051,2.139454,1.512653,2.212795,0.834400,0.792632,0.819192,0.790361,0.515553,...,219.997220,0.000000,213.570450,51.256510,135.764020,402.783360,0.000000,506.49070,0.000000,0.000000
68,68,3.539936,4.746236,2.362791,4.317878,0.592329,0.550715,0.651098,0.557557,0.195290,...,5.562061,242.176480,0.000000,87.790540,0.000000,0.000000,110.680950,95.39355,108.926600,0.000000
69,69,1.239461,2.144037,1.515135,2.220331,0.833448,0.791858,0.818391,0.789909,0.513758,...,32.707726,0.000000,64.865654,0.000000,0.000000,104.857130,144.280700,0.00000,72.189320,80.665710
70,70,4.173836,5.570488,2.883824,5.557985,0.576201,0.533531,0.623585,0.538065,0.202298,...,68.710690,0.000000,63.225480,170.037540,0.000000,291.640050,104.367615,228.50185,118.094160,0.000000

In [ ]:
df_combined=df_combined.sample(frac=1)

In [ ]:
df_combined.columns

Index(['Unnamed: 0', '0', '1', '2', '3', '4', '5', '6', '7', '8',
       ...
       '502', '503', '504', '505', '506', '507', '508', '509', '510', '511'],
      dtype='object', length=530)

In [ ]:
df_combined

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,502,503,504,505,506,507,508,509,510,511
12,12,2.547901,3.885444,2.839721,4.058439,0.656532,0.612246,0.647344,0.600434,0.255533,...,187.489320,0.000000,432.015500,121.97215,207.59848,0.00000,0.000000,147.339900,178.098130,66.354200
4,4,0.296477,0.546974,0.398545,0.584760,0.964779,0.956820,0.958611,0.953378,0.551095,...,0.000000,96.846535,0.000000,0.00000,268.96564,0.00000,96.542290,116.500990,0.000000,80.745804
27,27,4.056311,6.362261,5.512423,6.881799,0.530013,0.465003,0.480348,0.445821,0.141233,...,0.000000,216.809270,33.660534,381.43808,0.00000,160.68872,0.000000,104.384735,0.000000,244.593630
1,1,0.955086,1.737855,1.196538,1.742376,0.889324,0.865149,0.881835,0.860527,0.687369,...,50.051390,0.000000,0.000000,0.00000,0.00000,0.00000,42.633797,44.333330,163.358490,83.494090
34,34,1.646645,2.203614,1.209743,2.177855,0.707405,0.669277,0.754249,0.672434,0.276556,...,0.000000,0.000000,0.000000,0.00000,258.71176,0.00000,0.000000,11.499404,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6,6,4.712960,5.875340,3.684237,6.990188,0.649196,0.618829,0.674250,0.596389,0.345617,...,350.237600,196.612380,0.000000,0.00000,0.00000,0.00000,0.000000,60.950603,168.794270,337.969480
12,12,0.295665,0.536209,0.393336,0.574271,0.970326,0.963042,0.964706,0.961191,0.593848,...,0.000000,0.000000,0.000000,384.66300,0.00000,231.47054,0.000000,199.968350,88.630110,0.000000
27,27,0.760692,1.336271,0.692586,1.361584,0.835078,0.764196,0.890230,0.762732,0.405655,...,18.320300,469.549700,30.024480,436.67563,0.00000,0.00000,0.000000,0.000000,145.342000,164.940870
31,31,1.679075,3.266498,2.436765,3.367889,0.709244,0.615725,0.663165,0.612739,0.268792,...,26.832767,0.000000,57.441433,0.00000,0.00000,86.86717,300.710880,0.000000,159.209760,70.857860
27,27,1.794026,2.290058,1.462439,2.577147,0.728384,0.696854,0.749690,0.685895,0.333154,...,139.650150,306.975920,0.000000,0.00000,244.58066,0.00000,24.356098,0.000000,31.979944,211.727970

In [ ]:
df_combined.drop('Unnamed: 0',axis=1,inplace=True)

In [ ]:
cat_df=df_combined.select_dtypes(include="object")

In [ ]:
cat_df

                          16
12           Papaya Ringspot
4          Fresh Papaya Leaf
27           Papaya Ringspot
1            Papaya Ringspot
34           Papaya Ringspot
..                       ...
6          Papaya Black Spot
12         Fresh Papaya Leaf
27         Papaya Black Spot
31           Papaya Ringspot
27  Powdery Mildew of Papaya

[191 rows x 1 columns]

In [ ]:
encoders={}
for i in cat_df:
    encoders[i]=preprocessing.LabelEncoder()
    df_combined[i]=encoders[i].fit_transform(df_combined[i])

In [ ]:
df_combined['16'].unique()

array([3, 0, 1, 4, 2])

In [ ]:
df_combined.isnull()

,0,1,2,3,4,5,6,7,8,9,...,502,503,504,505,506,507,508,509,510,511
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
y=df_combined['16']
x=df_combined.drop("16",axis=1)

In [ ]:
x

,0,1,2,3,4,5,6,7,8,9,...,502,503,504,505,506,507,508,509,510,511
12,2.547901,3.885444,2.839721,4.058439,0.656532,0.612246,0.647344,0.600434,0.255533,0.245662,...,187.489320,0.000000,432.015500,121.97215,207.59848,0.00000,0.000000,147.339900,178.098130,66.354200
4,0.296477,0.546974,0.398545,0.584760,0.964779,0.956820,0.958611,0.953378,0.551095,0.546756,...,0.000000,96.846535,0.000000,0.00000,268.96564,0.00000,96.542290,116.500990,0.000000,80.745804
27,4.056311,6.362261,5.512423,6.881799,0.530013,0.465003,0.480348,0.445821,0.141233,0.127928,...,0.000000,216.809270,33.660534,381.43808,0.00000,160.68872,0.000000,104.384735,0.000000,244.593630
1,0.955086,1.737855,1.196538,1.742376,0.889324,0.865149,0.881835,0.860527,0.687369,0.681749,...,50.051390,0.000000,0.000000,0.00000,0.00000,0.00000,42.633797,44.333330,163.358490,83.494090
34,1.646645,2.203614,1.209743,2.177855,0.707405,0.669277,0.754249,0.672434,0.276556,0.260573,...,0.000000,0.000000,0.000000,0.00000,258.71176,0.00000,0.000000,11.499404,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6,4.712960,5.875340,3.684237,6.990188,0.649196,0.618829,0.674250,0.596389,0.345617,0.329649,...,350.237600,196.612380,0.000000,0.00000,0.00000,0.00000,0.000000,60.950603,168.794270,337.969480
12,0.295665,0.536209,0.393336,0.574271,0.970326,0.963042,0.964706,0.961191,0.593848,0.588435,...,0.000000,0.000000,0.000000,384.66300,0.00000,231.47054,0.000000,199.968350,88.630110,0.000000
27,0.760692,1.336271,0.692586,1.361584,0.835078,0.764196,0.890230,0.762732,0.405655,0.373758,...,18.320300,469.549700,30.024480,436.67563,0.00000,0.00000,0.000000,0.000000,145.342000,164.940870
31,1.679075,3.266498,2.436765,3.367889,0.709244,0.615725,0.663165,0.612739,0.268792,0.234459,...,26.832767,0.000000,57.441433,0.00000,0.00000,86.86717,300.710880,0.000000,159.209760,70.857860
27,1.794026,2.290058,1.462439,2.577147,0.728384,0.696854,0.749690,0.685895,0.333154,0.318284,...,139.650150,306.975920,0.000000,0.00000,244.58066,0.00000,24.356098,0.000000,31.979944,211.727970

In [ ]:
x.shape

(191, 528)

In [ ]:
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)

In [ ]:
x.shape

(191, 528)

In [ ]:
smote=SMOTE(sampling_strategy="minority")
x_sm,y_sm=smote.fit_resample(x_scaled,y)

In [ ]:


y_sm.value_counts()

3    71
0    71
4    48
1    28
2    23
Name: 16, dtype: int64

In [ ]:
x

,0,1,2,3,4,5,6,7,8,9,...,502,503,504,505,506,507,508,509,510,511
12,2.547901,3.885444,2.839721,4.058439,0.656532,0.612246,0.647344,0.600434,0.255533,0.245662,...,187.489320,0.000000,432.015500,121.97215,207.59848,0.00000,0.000000,147.339900,178.098130,66.354200
4,0.296477,0.546974,0.398545,0.584760,0.964779,0.956820,0.958611,0.953378,0.551095,0.546756,...,0.000000,96.846535,0.000000,0.00000,268.96564,0.00000,96.542290,116.500990,0.000000,80.745804
27,4.056311,6.362261,5.512423,6.881799,0.530013,0.465003,0.480348,0.445821,0.141233,0.127928,...,0.000000,216.809270,33.660534,381.43808,0.00000,160.68872,0.000000,104.384735,0.000000,244.593630
1,0.955086,1.737855,1.196538,1.742376,0.889324,0.865149,0.881835,0.860527,0.687369,0.681749,...,50.051390,0.000000,0.000000,0.00000,0.00000,0.00000,42.633797,44.333330,163.358490,83.494090
34,1.646645,2.203614,1.209743,2.177855,0.707405,0.669277,0.754249,0.672434,0.276556,0.260573,...,0.000000,0.000000,0.000000,0.00000,258.71176,0.00000,0.000000,11.499404,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6,4.712960,5.875340,3.684237,6.990188,0.649196,0.618829,0.674250,0.596389,0.345617,0.329649,...,350.237600,196.612380,0.000000,0.00000,0.00000,0.00000,0.000000,60.950603,168.794270,337.969480
12,0.295665,0.536209,0.393336,0.574271,0.970326,0.963042,0.964706,0.961191,0.593848,0.588435,...,0.000000,0.000000,0.000000,384.66300,0.00000,231.47054,0.000000,199.968350,88.630110,0.000000
27,0.760692,1.336271,0.692586,1.361584,0.835078,0.764196,0.890230,0.762732,0.405655,0.373758,...,18.320300,469.549700,30.024480,436.67563,0.00000,0.00000,0.000000,0.000000,145.342000,164.940870
31,1.679075,3.266498,2.436765,3.367889,0.709244,0.615725,0.663165,0.612739,0.268792,0.234459,...,26.832767,0.000000,57.441433,0.00000,0.00000,86.86717,300.710880,0.000000,159.209760,70.857860
27,1.794026,2.290058,1.462439,2.577147,0.728384,0.696854,0.749690,0.685895,0.333154,0.318284,...,139.650150,306.975920,0.000000,0.00000,244.58066,0.00000,24.356098,0.000000,31.979944,211.727970

In [ ]:
columns=x.columns
for i in columns:
  x[i]=x[i].replace(0,x[i].max())

In [ ]:
x

,0,1,2,3,4,5,6,7,8,9,...,502,503,504,505,506,507,508,509,510,511
12,2.547901,3.885444,2.839721,4.058439,0.656532,0.612246,0.647344,0.600434,0.255533,0.245662,...,187.489320,87.238616,432.015500,121.972150,207.598480,71.592441,70.282775,147.339900,178.098130,66.354200
4,0.296477,0.546974,0.398545,0.584760,0.964779,0.956820,0.958611,0.953378,0.551095,0.546756,...,68.786029,96.846535,72.310179,69.884792,268.965640,71.592441,96.542290,116.500990,78.779505,80.745804
27,4.056311,6.362261,5.512423,6.881799,0.530013,0.465003,0.480348,0.445821,0.141233,0.127928,...,68.786029,216.809270,33.660534,381.438080,80.284156,160.688720,70.282775,104.384735,78.779505,244.593630
1,0.955086,1.737855,1.196538,1.742376,0.889324,0.865149,0.881835,0.860527,0.687369,0.681749,...,50.051390,87.238616,72.310179,69.884792,80.284156,71.592441,42.633797,44.333330,163.358490,83.494090
34,1.646645,2.203614,1.209743,2.177855,0.707405,0.669277,0.754249,0.672434,0.276556,0.260573,...,68.786029,87.238616,72.310179,69.884792,258.711760,71.592441,70.282775,11.499404,78.779505,83.310048
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6,4.712960,5.875340,3.684237,6.990188,0.649196,0.618829,0.674250,0.596389,0.345617,0.329649,...,350.237600,196.612380,72.310179,69.884792,80.284156,71.592441,70.282775,60.950603,168.794270,337.969480
12,0.295665,0.536209,0.393336,0.574271,0.970326,0.963042,0.964706,0.961191,0.593848,0.588435,...,68.786029,87.238616,72.310179,384.663000,80.284156,231.470540,70.282775,199.968350,88.630110,83.310048
27,0.760692,1.336271,0.692586,1.361584,0.835078,0.764196,0.890230,0.762732,0.405655,0.373758,...,18.320300,469.549700,30.024480,436.675630,80.284156,71.592441,70.282775,82.264677,145.342000,164.940870
31,1.679075,3.266498,2.436765,3.367889,0.709244,0.615725,0.663165,0.612739,0.268792,0.234459,...,26.832767,87.238616,57.441433,69.884792,80.284156,86.867170,300.710880,82.264677,159.209760,70.857860
27,1.794026,2.290058,1.462439,2.577147,0.728384,0.696854,0.749690,0.685895,0.333154,0.318284,...,139.650150,306.975920,72.310179,69.884792,244.580660,71.592441,24.356098,82.264677,31.979944,211.727970

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x_sm,y_sm,stratify=y_sm)

In [ ]:
forest=RandomForestClassifier(n_estimators=400,criterion="gini",max_depth=5)

In [ ]:
forest.fit(x_train,y_train)

RandomForestClassifier(max_depth=5, n_estimators=400)

In [ ]:
pred_f=forest.predict(x_test)

In [ ]:
print(classification_report(y_test,pred_f))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       0.00      0.00      0.00         7
           2       0.00      0.00      0.00         6
           3       0.70      0.89      0.78        18
           4       0.45      0.75      0.56        12

    accuracy                           0.70        61
   macro avg       0.43      0.53      0.47        61
weighted avg       0.59      0.70      0.64        61

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [ ]:


clf=GridSearchCV(RandomForestClassifier(),{
    "n_estimators":[10,100,200,300,400,500,600,700,800],
    "criterion":["gini","entropy"]
},cv=5,return_train_score=False)
clf.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'n_estimators': [10, 100, 200, 300, 400, 500, 600, 700,
                                          800]})

In [ ]:
df5=pd.DataFrame(clf.cv_results_)

In [ ]:
df5

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.024738,0.004462,0.002525,0.000401,gini,10,"{'criterion': 'gini', 'n_estimators': 10}",0.555556,0.611111,0.638889,0.500000,0.666667,0.594444,0.059835,18
1,0.229292,0.019118,0.023635,0.011609,gini,100,"{'criterion': 'gini', 'n_estimators': 100}",0.666667,0.722222,0.583333,0.611111,0.722222,0.661111,0.056656,9
2,0.413234,0.006056,0.030013,0.002643,gini,200,"{'criterion': 'gini', 'n_estimators': 200}",0.638889,0.777778,0.638889,0.611111,0.666667,0.666667,0.058267,7
3,0.630114,0.007603,0.045781,0.005416,gini,300,"{'criterion': 'gini', 'n_estimators': 300}",0.666667,0.750000,0.583333,0.611111,0.750000,0.672222,0.068943,3
4,0.838614,0.012830,0.056742,0.003137,gini,400,"{'criterion': 'gini', 'n_estimators': 400}",0.666667,0.694444,0.583333,0.611111,0.722222,0.655556,0.051520,12
5,1.056104,0.012302,0.071815,0.000872,gini,500,"{'criterion': 'gini', 'n_estimators': 500}",0.694444,0.750000,0.611111,0.666667,0.722222,0.688889,0.047791,1
6,1.262458,0.027806,0.093087,0.005865,gini,600,"{'criterion': 'gini', 'n_estimators': 600}",0.638889,0.694444,0.611111,0.638889,0.722222,0.661111,0.040825,11
7,1.462709,0.008750,0.113076,0.005745,gini,700,"{'criterion': 'gini', 'n_estimators': 700}",0.694444,0.722222,0.611111,0.638889,0.750000,0.683333,0.051520,2
8,1.666180,0.010434,0.130590,0.023373,gini,800,"{'criterion': 'gini', 'n_estimators': 800}",0.694444,0.722222,0.583333,0.611111,0.750000,0.672222,0.064310,3
9,0.034231,0.003655,0.002428,0.000089,entropy,10,"{'criterion': 'entropy', 'n_estimators': 10}",0.638889,0.722222,0.638889,0.527778,0.666667,0.638889,0.063343,17
10,0.315047,0.009647,0.016113,0.001177,entropy,100,"{'criterion': 'entropy', 'n_estimators': 100}",0.666667,0.694444,0.611111,0.611111,0.694444,0.655556,0.037680,13
11,0.642296,0.015700,0.036001,0.010880,entropy,200,"{'criterion': 'entropy', 'n_estimators': 200}",0.666667,0.666667,0.611111,0.583333,0.694444,0.644444,0.040825,16
12,0.949853,0.009673,0.050604,0.007298,entropy,300,"{'criterion': 'entropy', 'n_estimators': 300}",0.638889,0.694444,0.666667,0.638889,0.694444,0.666667,0.024845,7
13,1.256354,0.010327,0.063079,0.006258,entropy,400,"{'criterion': 'entropy', 'n_estimators': 400}",0.666667,0.638889,0.638889,0.638889,0.694444,0.655556,0.022222,13
14,1.569632,0.013151,0.083205,0.007060,entropy,500,"{'criterion': 'entropy', 'n_estimators': 500}",0.638889,0.694444,0.611111,0.583333,0.722222,0.650000,0.051520,15
15,1.882910,0.015030,0.096005,0.008626,entropy,600,"{'criterion': 'entropy', 'n_estimators': 600}",0.666667,0.750000,0.583333,0.638889,0.722222,0.672222,0.059317,3
16,2.295783,0.219164,0.108335,0.005257,entropy,700,"{'criterion': 'entropy', 'n_estimators': 700}",0.666667,0.694444,0.638889,0.583333,0.722222,0.661111,0.047791,9
17,2.636995,0.266795,0.122658,0.010978,entropy,800,"{'criterion': 'entropy', 'n_estimators': 800}",0.666667,0.722222,0.638889,0.611111,0.722222,0.672222,0.044444,3

In [ ]:
print("Accuracy:",metrics.accuracy_score(y_test, pred_f))

Accuracy: 0.7049180327868853

In [ ]:
svm1=svm.SVC(gamma="auto",C=10,kernel="rbf",probability=True)

In [ ]:
svm1.fit(x_train,y_train)
pred_s=svm1.predict(x_test)

In [ ]:
print(classification_report(y_test,pred_s))

              precision    recall  f1-score   support

           0       0.95      1.00      0.97        18
           1       0.00      0.00      0.00         7
           2       0.00      0.00      0.00         6
           3       0.46      0.94      0.62        18
           4       0.20      0.08      0.12        12

    accuracy                           0.59        61
   macro avg       0.32      0.41      0.34        61
weighted avg       0.45      0.59      0.49        61

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [ ]:
print("Accuracy:",metrics.accuracy_score(y_test, pred_s))

Accuracy: 0.5901639344262295

In [ ]:


clf_svm=GridSearchCV(svm.SVC(gamma="auto"),{
    "C":[1,10,20],
    "kernel":["linear","rbf"]
},cv=5,return_train_score=False)
clf_svm.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20], 'kernel': ['linear', 'rbf']})

In [ ]:
df5=pd.DataFrame(clf_svm.cv_results_)

In [ ]:


df5

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.007884,0.001108,0.001330,0.000066,1,linear,"{'C': 1, 'kernel': 'linear'}",0.472222,0.611111,0.583333,0.500000,0.666667,0.566667,0.071578,1
1,0.009196,0.001455,0.002632,0.000286,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.583333,0.527778,0.527778,0.555556,0.611111,0.561111,0.032394,5
2,0.006890,0.000101,0.001267,0.000036,10,linear,"{'C': 10, 'kernel': 'linear'}",0.472222,0.611111,0.583333,0.500000,0.666667,0.566667,0.071578,1
3,0.009014,0.000174,0.002549,0.000438,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.583333,0.611111,0.555556,0.472222,0.583333,0.561111,0.047791,5
4,0.007013,0.000093,0.001381,0.000095,20,linear,"{'C': 20, 'kernel': 'linear'}",0.472222,0.611111,0.583333,0.500000,0.666667,0.566667,0.071578,1
5,0.009708,0.000995,0.002711,0.000614,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.500000,0.611111,0.611111,0.472222,0.638889,0.566667,0.067128,1

In [ ]:
classifier=AdaBoostClassifier(DecisionTreeClassifier(criterion="gini"),algorithm="SAMME.R",
                         n_estimators=200)
classifier.fit(x_train,y_train)
pred_a=classifier.predict(x_test)

In [ ]:
print(confusion_matrix(y_test,pred_a))
print(classification_report(y_test,pred_a))
print("Accuracy:",metrics.accuracy_score(y_test, pred_a))

[[18  0  0  0  0]
 [ 0  2  1  3  1]
 [ 0  2  0  3  1]
 [ 0  0  0 16  2]
 [ 0  0  3  4  5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       0.50      0.29      0.36         7
           2       0.00      0.00      0.00         6
           3       0.62      0.89      0.73        18
           4       0.56      0.42      0.48        12

    accuracy                           0.67        61
   macro avg       0.53      0.52      0.51        61
weighted avg       0.64      0.67      0.65        61

Accuracy: 0.6721311475409836

In [ ]:
gnb=GaussianNB()
gnb.fit(x_train,y_train)
pred_n=gnb.predict(x_test)

In [ ]:
print(confusion_matrix(y_test,pred_n))
print(classification_report(y_test,pred_n))
print("Accuracy:",metrics.accuracy_score(y_test,pred_n))

[[17  0  0  1  0]
 [ 0  0  0  5  2]
 [ 0  0  0  4  2]
 [ 0  0  0 15  3]
 [ 0  0  0  7  5]]
              precision    recall  f1-score   support

           0       1.00      0.94      0.97        18
           1       0.00      0.00      0.00         7
           2       0.00      0.00      0.00         6
           3       0.47      0.83      0.60        18
           4       0.42      0.42      0.42        12

    accuracy                           0.61        61
   macro avg       0.38      0.44      0.40        61
weighted avg       0.52      0.61      0.55        61

Accuracy: 0.6065573770491803

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [ ]:
 from sklearn.neural_network import MLPClassifier

In [ ]:
clf = MLPClassifier(random_state=1, max_iter=300).fit(x_train, y_train)

In [ ]:
pred_m=clf.predict(x_test)

In [ ]:
print(confusion_matrix(y_test,pred_m))
print(classification_report(y_test,pred_m))
print("Accuracy:",metrics.accuracy_score(y_test,pred_m))

[[17  0  0  0  1]
 [ 0  0  1  4  2]
 [ 0  3  0  2  1]
 [ 0  0  0 13  5]
 [ 0  1  2  8  1]]
              precision    recall  f1-score   support

           0       1.00      0.94      0.97        18
           1       0.00      0.00      0.00         7
           2       0.00      0.00      0.00         6
           3       0.48      0.72      0.58        18
           4       0.10      0.08      0.09        12

    accuracy                           0.51        61
   macro avg       0.32      0.35      0.33        61
weighted avg       0.46      0.51      0.48        61

Accuracy: 0.5081967213114754

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

clf = GradientBoostingClassifier(n_estimators=1000, learning_rate=0.0001, max_depth=5, random_state=0).fit(x_train, y_train)
clf.score(x_test, y_test)

0.6065573770491803