In [ ]:
from google.colab import drive
drive.mount('/content/drive')


%cd /content/drive/MyDrive/ML_DATASET/papaya/Fresh Papaya Leaf/clahe

import numpy as np                       
import tensorflow as tf
import matplotlib.pyplot as plt
from numpy import linalg as LA

from sklearn.preprocessing import StandardScaler



from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_curve, auc

Mounted at /content/drive
/content/drive/MyDrive/ML_DATASET/papaya/Fresh Papaya Leaf/clahe

In [ ]:
import glob
import cv2 as cv
import pandas as pd
import numpy as np
images4=[cv.imread(file,cv.IMREAD_UNCHANGED) for file in sorted(glob.glob(r"/content/drive/MyDrive/ML_DATASET/papaya/Papaya Ringspot/clahe/*.png"))]

In [ ]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
li=[]

for i,img in enumerate(images4):
    model = Sequential()
    model.add(Dense(1024, activation='relu', kernel_initializer='he_normal', input_shape=(65536,)))
    model.add(Dense(512, activation='relu', kernel_initializer='he_normal'))
    # compile the model
    model.compile()
    # fit the model
    img=img.reshape(1,256*256)
    img=img.astype('float64')
  
    from tensorflow.keras import backend as K
    layerIndex = 1
    func = K.function([model.get_layer(index=0).input], model.get_layer(index=layerIndex).output)
    layerOutput = func([img])  # input_data is a numpy array
    
    li.append(layerOutput[0])

In [ ]:
df=pd.DataFrame(li)

In [ ]:
df

,0,1,2,3,4,5,6,7,8,9,...,502,503,504,505,506,507,508,509,510,511
0,80.591614,0.000000,0.000000,0.000000,134.408279,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,41.692829,0.000000,0.000000,0.000000,0.000000,173.529373,0.000000
1,118.225616,6.413311,63.820107,272.155518,0.000000,0.000000,86.341118,0.000000,134.489746,93.548828,...,50.051392,0.000000,0.000000,0.000000,0.000000,0.000000,42.633797,44.333328,163.358490,83.494087
2,0.000000,178.091919,17.821129,42.683681,50.356873,339.082947,0.000000,9.050917,74.010559,0.000000,...,1.117848,0.000000,192.351578,86.196800,98.246307,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,86.715729,0.000000,...,0.000000,21.866322,179.667923,0.000000,138.308304,49.427021,128.426971,199.000336,0.000000,259.936340
4,49.989212,0.000000,230.364807,1.279979,86.766884,0.000000,271.896698,0.000000,189.035187,0.000000,...,165.914215,155.079498,0.000000,208.801147,82.172958,0.000000,36.137054,38.679886,179.616531,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,0.000000,338.118195,0.000000,194.035629,177.559341,0.000000,368.966278,252.697845,0.000000,401.659790,...,0.000000,0.000000,103.233734,15.188221,35.710697,275.709808,0.000000,0.000000,71.536674,259.301605
67,0.000000,0.000000,173.334900,293.779144,227.063904,18.294266,0.000000,392.225708,10.473745,0.000000,...,219.997223,0.000000,213.570450,51.256512,135.764023,402.783356,0.000000,506.490692,0.000000,0.000000
68,0.000000,98.919350,8.618435,0.000000,0.000000,0.000000,0.000000,0.000000,7.683044,0.000000,...,5.562061,242.176483,0.000000,87.790543,0.000000,0.000000,110.680946,95.393547,108.926598,0.000000
69,0.000000,137.731705,306.559814,0.000000,0.000000,0.000000,18.338095,16.086533,0.000000,242.499023,...,32.707726,0.000000,64.865654,0.000000,0.000000,104.857132,144.280701,0.000000,72.189323,80.665710
70,0.000000,0.000000,40.143005,270.477997,0.000000,0.000000,0.012215,192.261581,0.000000,0.000000,...,68.710693,0.000000,63.225479,170.037537,0.000000,291.640045,104.367615,228.501846,118.094162,0.000000

In [ ]:
df1=pd.read_csv(r"/content/drive/MyDrive/ML_DATASET/papaya/Papaya-Ringspot.csv")

In [ ]:
df1

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,0,0.709835,1.329504,0.869715,1.086059,0.890491,0.861924,0.885957,0.873923,0.484129,0.475094,0.482804,0.478438,0.974950,0.953210,0.969345,0.961779,Papaya Ringspot
1,1,0.955086,1.737855,1.196538,1.742376,0.889324,0.865149,0.881835,0.860527,0.687369,0.681749,0.686871,0.682581,0.968506,0.942738,0.960495,0.942599,Papaya Ringspot
2,2,2.091330,2.982514,1.472350,2.735948,0.766992,0.743936,0.799354,0.744798,0.443408,0.435735,0.450814,0.436828,0.937073,0.910264,0.955705,0.917675,Papaya Ringspot
3,3,1.238143,1.788789,1.103983,2.029466,0.865595,0.842575,0.878024,0.842311,0.635163,0.629989,0.637528,0.629142,0.961578,0.944551,0.965750,0.937091,Papaya Ringspot
4,4,2.189706,4.226621,2.971890,4.091442,0.691348,0.595699,0.642363,0.602276,0.262783,0.229725,0.247064,0.232641,0.898678,0.804452,0.862591,0.810715,Papaya Ringspot
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,66,3.169072,3.498624,1.728493,4.318431,0.619404,0.605221,0.703047,0.575884,0.218107,0.211497,0.241383,0.202438,0.878929,0.866276,0.933911,0.834941,Papaya Ringspot
67,67,1.238051,2.139454,1.512653,2.212795,0.834400,0.792632,0.819192,0.790361,0.515553,0.505965,0.513147,0.504479,0.966796,0.942678,0.959431,0.940713,Papaya Ringspot
68,68,3.539936,4.746236,2.362791,4.317878,0.592329,0.550715,0.651098,0.557557,0.195290,0.182038,0.212193,0.182812,0.847623,0.795698,0.898268,0.814142,Papaya Ringspot
69,69,1.239461,2.144037,1.515135,2.220331,0.833448,0.791858,0.818391,0.789909,0.513758,0.504054,0.511349,0.502634,0.966832,0.942682,0.959454,0.940642,Papaya Ringspot
70,70,4.173836,5.570488,2.883824,5.557985,0.576201,0.533531,0.623585,0.538065,0.202298,0.188613,0.215171,0.189952,0.856153,0.808247,0.900712,0.808665,Papaya Ringspot

In [ ]:
df_concat = pd.concat([df1, df], axis=1)

In [ ]:
df_concat

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,502,503,504,505,506,507,508,509,510,511
0,0,0.709835,1.329504,0.869715,1.086059,0.890491,0.861924,0.885957,0.873923,0.484129,...,0.000000,0.000000,0.000000,41.692829,0.000000,0.000000,0.000000,0.000000,173.529373,0.000000
1,1,0.955086,1.737855,1.196538,1.742376,0.889324,0.865149,0.881835,0.860527,0.687369,...,50.051392,0.000000,0.000000,0.000000,0.000000,0.000000,42.633797,44.333328,163.358490,83.494087
2,2,2.091330,2.982514,1.472350,2.735948,0.766992,0.743936,0.799354,0.744798,0.443408,...,1.117848,0.000000,192.351578,86.196800,98.246307,0.000000,0.000000,0.000000,0.000000,0.000000
3,3,1.238143,1.788789,1.103983,2.029466,0.865595,0.842575,0.878024,0.842311,0.635163,...,0.000000,21.866322,179.667923,0.000000,138.308304,49.427021,128.426971,199.000336,0.000000,259.936340
4,4,2.189706,4.226621,2.971890,4.091442,0.691348,0.595699,0.642363,0.602276,0.262783,...,165.914215,155.079498,0.000000,208.801147,82.172958,0.000000,36.137054,38.679886,179.616531,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,66,3.169072,3.498624,1.728493,4.318431,0.619404,0.605221,0.703047,0.575884,0.218107,...,0.000000,0.000000,103.233734,15.188221,35.710697,275.709808,0.000000,0.000000,71.536674,259.301605
67,67,1.238051,2.139454,1.512653,2.212795,0.834400,0.792632,0.819192,0.790361,0.515553,...,219.997223,0.000000,213.570450,51.256512,135.764023,402.783356,0.000000,506.490692,0.000000,0.000000
68,68,3.539936,4.746236,2.362791,4.317878,0.592329,0.550715,0.651098,0.557557,0.195290,...,5.562061,242.176483,0.000000,87.790543,0.000000,0.000000,110.680946,95.393547,108.926598,0.000000
69,69,1.239461,2.144037,1.515135,2.220331,0.833448,0.791858,0.818391,0.789909,0.513758,...,32.707726,0.000000,64.865654,0.000000,0.000000,104.857132,144.280701,0.000000,72.189323,80.665710
70,70,4.173836,5.570488,2.883824,5.557985,0.576201,0.533531,0.623585,0.538065,0.202298,...,68.710693,0.000000,63.225479,170.037537,0.000000,291.640045,104.367615,228.501846,118.094162,0.000000

In [ ]:
df_concat.drop('Unnamed: 0',axis=1,inplace=True)

In [ ]:
df_concat

,0,1,2,3,4,5,6,7,8,9,...,502,503,504,505,506,507,508,509,510,511
0,0.709835,1.329504,0.869715,1.086059,0.890491,0.861924,0.885957,0.873923,0.484129,0.475094,...,0.000000,0.000000,0.000000,41.692829,0.000000,0.000000,0.000000,0.000000,173.529373,0.000000
1,0.955086,1.737855,1.196538,1.742376,0.889324,0.865149,0.881835,0.860527,0.687369,0.681749,...,50.051392,0.000000,0.000000,0.000000,0.000000,0.000000,42.633797,44.333328,163.358490,83.494087
2,2.091330,2.982514,1.472350,2.735948,0.766992,0.743936,0.799354,0.744798,0.443408,0.435735,...,1.117848,0.000000,192.351578,86.196800,98.246307,0.000000,0.000000,0.000000,0.000000,0.000000
3,1.238143,1.788789,1.103983,2.029466,0.865595,0.842575,0.878024,0.842311,0.635163,0.629989,...,0.000000,21.866322,179.667923,0.000000,138.308304,49.427021,128.426971,199.000336,0.000000,259.936340
4,2.189706,4.226621,2.971890,4.091442,0.691348,0.595699,0.642363,0.602276,0.262783,0.229725,...,165.914215,155.079498,0.000000,208.801147,82.172958,0.000000,36.137054,38.679886,179.616531,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,3.169072,3.498624,1.728493,4.318431,0.619404,0.605221,0.703047,0.575884,0.218107,0.211497,...,0.000000,0.000000,103.233734,15.188221,35.710697,275.709808,0.000000,0.000000,71.536674,259.301605
67,1.238051,2.139454,1.512653,2.212795,0.834400,0.792632,0.819192,0.790361,0.515553,0.505965,...,219.997223,0.000000,213.570450,51.256512,135.764023,402.783356,0.000000,506.490692,0.000000,0.000000
68,3.539936,4.746236,2.362791,4.317878,0.592329,0.550715,0.651098,0.557557,0.195290,0.182038,...,5.562061,242.176483,0.000000,87.790543,0.000000,0.000000,110.680946,95.393547,108.926598,0.000000
69,1.239461,2.144037,1.515135,2.220331,0.833448,0.791858,0.818391,0.789909,0.513758,0.504054,...,32.707726,0.000000,64.865654,0.000000,0.000000,104.857132,144.280701,0.000000,72.189323,80.665710
70,4.173836,5.570488,2.883824,5.557985,0.576201,0.533531,0.623585,0.538065,0.202298,0.188613,...,68.710693,0.000000,63.225479,170.037537,0.000000,291.640045,104.367615,228.501846,118.094162,0.000000

In [ ]:
df_concat.to_csv("/content/drive/MyDrive/ML_DATASET/papaya/ring_spot_hand_deep.csv")